apiVersion: apps/v1
kind: Deployment
metadata:
  name: sparkoperator
spec:
  template:
    spec:
      serviceAccountName: sparkoperator
      containers:
      - name: sparkoperator
        imagePullPolicy: IfNotPresent