apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/version: v2.4.4-v1beta2
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: spark-operator

bases:
  - spark
  - spark-operator

resources:
  - crds/sparkoperator.k8s.io_scheduledsparkapplications.yaml
  - crds/sparkoperator.k8s.io_sparkapplications.yaml

images:
  - name: sparkoperator
    newTag: v1beta2-1.0.0-2.4.4
    digest: sha256:52b257911a5c47c480aae25f83c80151a2ed8c99e8b50317d451c157c80666fd

replicas:
  - name: sparkoperator
    count: 3

patches:
  # set imagePullPolicy to "IfNotPresent"
  - path: patches/patch_image_pull_policy.yaml
    target:
      kind: Deployment
  # add Prometheus monitoring
  - path: patches/patch_add_monitoring.yaml
    target:
      kind: Deployment
  # use HA leader election
  - path: patches/patch_use_leader_election.yaml
    target:
      kind: Deployment
